/** Auto-generated by scripts/apply_portfolio.py */

export type ProjectGroupId = "kitchens" | "hallways" | "sofas";

export interface PortfolioCollection {
  id: string;
  style: string;
  layout: string;
  images: string[];
}

export interface ProjectGroup {
  id: ProjectGroupId;
  title: string;
  cover: string;
  /** Три ракурса для карточки раздела: общий, перспектива, деталь */
  showcase: string[];
  collections: PortfolioCollection[];
}

export const PORTFOLIO_VERSION = "11";

export const projectGroups: ProjectGroup[] = [
  {
    "id": "kitchens",
    "title": "Кухни",
    "cover": "/images/portfolio/kitchens/cover.jpg?v=11",
    "showcase": [
      "/images/portfolio/kitchens/cover.jpg?v=11",
      "/images/portfolio/kitchens/showcase-02.jpg?v=11",
      "/images/portfolio/kitchens/showcase-03.jpg?v=11"
    ],
    "collections": [
      {
        "id": "kitchen-01",
        "style": "неоклассика",
        "layout": "угловая с островом",
        "images": [
          "/images/portfolio/kitchens/kitchen-01/01.jpg?v=11",
          "/images/portfolio/kitchens/kitchen-01/02.jpg?v=11",
          "/images/portfolio/kitchens/kitchen-01/03.jpg?v=11"
        ]
      },
      {
        "id": "kitchen-02",
        "style": "неоклассика",
        "layout": "угловая",
        "images": [
          "/images/portfolio/kitchens/kitchen-02/01.jpg?v=11",
          "/images/portfolio/kitchens/kitchen-02/02.jpg?v=11",
          "/images/portfolio/kitchens/kitchen-02/03.jpg?v=11"
        ]
      },
      {
        "id": "kitchen-03",
        "style": "неоклассика",
        "layout": "прямая",
        "images": [
          "/images/portfolio/kitchens/kitchen-03/01.jpg?v=11",
          "/images/portfolio/kitchens/kitchen-03/02.jpg?v=11",
          "/images/portfolio/kitchens/kitchen-03/03.jpg?v=11"
        ]
      },
      {
        "id": "kitchen-04",
        "style": "современный",
        "layout": "угловая",
        "images": [
          "/images/portfolio/kitchens/kitchen-04/01.jpg?v=11",
          "/images/portfolio/kitchens/kitchen-04/02.jpg?v=11",
          "/images/portfolio/kitchens/kitchen-04/03.jpg?v=11"
        ]
      },
      {
        "id": "kitchen-05",
        "style": "современный",
        "layout": "прямая",
        "images": [
          "/images/portfolio/kitchens/kitchen-05/01.jpg?v=11",
          "/images/portfolio/kitchens/kitchen-05/02.jpg?v=11",
          "/images/portfolio/kitchens/kitchen-05/03.jpg?v=11"
        ]
      },
      {
        "id": "kitchen-06",
        "style": "современный",
        "layout": "П-образная с барной стойкой",
        "images": [
          "/images/portfolio/kitchens/kitchen-06/01.jpg?v=11",
          "/images/portfolio/kitchens/kitchen-06/02.jpg?v=11",
          "/images/portfolio/kitchens/kitchen-06/03.jpg?v=11"
        ]
      },
      {
        "id": "kitchen-07",
        "style": "современный",
        "layout": "прямая",
        "images": [
          "/images/portfolio/kitchens/kitchen-07/01.jpg?v=11",
          "/images/portfolio/kitchens/kitchen-07/02.jpg?v=11",
          "/images/portfolio/kitchens/kitchen-07/03.jpg?v=11"
        ]
      },
      {
        "id": "kitchen-08",
        "style": "современный",
        "layout": "угловая",
        "images": [
          "/images/portfolio/kitchens/kitchen-08/01.jpg?v=11",
          "/images/portfolio/kitchens/kitchen-08/02.jpg?v=11",
          "/images/portfolio/kitchens/kitchen-08/03.jpg?v=11"
        ]
      },
      {
        "id": "kitchen-09",
        "style": "неоклассика",
        "layout": "с островом",
        "images": [
          "/images/portfolio/kitchens/kitchen-09/01.jpg?v=12",
          "/images/portfolio/kitchens/kitchen-09/02.jpg?v=12",
          "/images/portfolio/kitchens/kitchen-09/03.jpg?v=12"
        ]
      }
    ]
  },
  {
    "id": "hallways",
    "title": "Прихожие",
    "cover": "/images/portfolio/hallways/cover.jpg?v=11",
    "showcase": [
      "/images/portfolio/hallways/cover.jpg?v=11",
      "/images/portfolio/hallways/showcase-02.jpg?v=11",
      "/images/portfolio/hallways/showcase-03.jpg?v=11"
    ],
    "collections": [
      {
        "id": "hallway-01",
        "style": "неоклассика",
        "layout": "с зеркалом и сиденьем",
        "images": [
          "/images/portfolio/hallways/hallway-01/01.jpg?v=11",
          "/images/portfolio/hallways/hallway-01/02.jpg?v=11",
          "/images/portfolio/hallways/hallway-01/03.jpg?v=11"
        ]
      },
      {
        "id": "hallway-02",
        "style": "классика",
        "layout": "с зеркалом и банкеткой",
        "images": [
          "/images/portfolio/hallways/hallway-02/01.jpg?v=11",
          "/images/portfolio/hallways/hallway-02/02.jpg?v=11",
          "/images/portfolio/hallways/hallway-02/03.jpg?v=11"
        ]
      },
      {
        "id": "hallway-03",
        "style": "современный",
        "layout": "с круглым зеркалом",
        "images": [
          "/images/portfolio/hallways/hallway-03/01.jpg?v=11",
          "/images/portfolio/hallways/hallway-03/02.jpg?v=11",
          "/images/portfolio/hallways/hallway-03/03.jpg?v=11"
        ]
      },
      {
        "id": "hallway-04",
        "style": "современный",
        "layout": "модульная с рейками",
        "images": [
          "/images/portfolio/hallways/hallway-04/01.jpg?v=11",
          "/images/portfolio/hallways/hallway-04/02.jpg?v=11",
          "/images/portfolio/hallways/hallway-04/03.jpg?v=11"
        ]
      },
      {
        "id": "hallway-05",
        "style": "современный",
        "layout": "с мягкой панелью",
        "images": [
          "/images/portfolio/hallways/hallway-05/01.jpg?v=11",
          "/images/portfolio/hallways/hallway-05/02.jpg?v=11",
          "/images/portfolio/hallways/hallway-05/03.jpg?v=11"
        ]
      },
      {
        "id": "hallway-06",
        "style": "современный",
        "layout": "с зеркалом",
        "images": [
          "/images/portfolio/hallways/hallway-06/01.jpg?v=11",
          "/images/portfolio/hallways/hallway-06/02.jpg?v=11",
          "/images/portfolio/hallways/hallway-06/03.jpg?v=11"
        ]
      },
      {
        "id": "hallway-07",
        "style": "неоклассика",
        "layout": "модульная",
        "images": [
          "/images/portfolio/hallways/hallway-07/01.jpg?v=11",
          "/images/portfolio/hallways/hallway-07/02.jpg?v=11",
          "/images/portfolio/hallways/hallway-07/03.jpg?v=11"
        ]
      },
      {
        "id": "hallway-08",
        "style": "классика",
        "layout": "модульная",
        "images": [
          "/images/portfolio/hallways/hallway-08/01.jpg?v=11",
          "/images/portfolio/hallways/hallway-08/02.jpg?v=11",
          "/images/portfolio/hallways/hallway-08/03.jpg?v=11"
        ]
      }
    ]
  },
  {
    "id": "sofas",
    "title": "Диваны",
    "cover": "/images/portfolio/sofas/cover.jpg?v=11",
    "showcase": [
      "/images/portfolio/sofas/cover.jpg?v=11",
      "/images/portfolio/sofas/showcase-02.jpg?v=11",
      "/images/portfolio/sofas/showcase-03.jpg?v=11"
    ],
    "collections": [
      {
        "id": "sofa-02",
        "style": "современный",
        "layout": "прямой",
        "images": [
          "/images/portfolio/sofas/sofa-02/01.jpg?v=11",
          "/images/portfolio/sofas/sofa-02/02.jpg?v=11",
          "/images/portfolio/sofas/sofa-02/03.jpg?v=11"
        ]
      },
      {
        "id": "sofa-03",
        "style": "неоклассика",
        "layout": "прямой",
        "images": [
          "/images/portfolio/sofas/sofa-03/01.jpg?v=11",
          "/images/portfolio/sofas/sofa-03/02.jpg?v=11",
          "/images/portfolio/sofas/sofa-03/03.jpg?v=11"
        ]
      },
      {
        "id": "sofa-04",
        "style": "современный",
        "layout": "прямой",
        "images": [
          "/images/portfolio/sofas/sofa-04/01.jpg?v=11",
          "/images/portfolio/sofas/sofa-04/02.jpg?v=11",
          "/images/portfolio/sofas/sofa-04/03.jpg?v=11"
        ]
      },
      {
        "id": "sofa-05",
        "style": "классика",
        "layout": "прямой",
        "images": [
          "/images/portfolio/sofas/sofa-05/01.jpg?v=11",
          "/images/portfolio/sofas/sofa-05/02.jpg?v=11",
          "/images/portfolio/sofas/sofa-05/03.jpg?v=11"
        ]
      },
      {
        "id": "sofa-06",
        "style": "классика",
        "layout": "кресло",
        "images": [
          "/images/portfolio/sofas/sofa-06/01.jpg?v=11",
          "/images/portfolio/sofas/sofa-06/02.jpg?v=11",
          "/images/portfolio/sofas/sofa-06/03.jpg?v=11"
        ]
      },
      {
        "id": "sofa-07",
        "style": "современный",
        "layout": "прямой",
        "images": [
          "/images/portfolio/sofas/sofa-07/01.jpg?v=11",
          "/images/portfolio/sofas/sofa-07/02.jpg?v=11",
          "/images/portfolio/sofas/sofa-07/03.jpg?v=11"
        ]
      },
      {
        "id": "sofa-08",
        "style": "классика",
        "layout": "прямой",
        "images": [
          "/images/portfolio/sofas/sofa-08/01.jpg?v=11",
          "/images/portfolio/sofas/sofa-08/02.jpg?v=11",
          "/images/portfolio/sofas/sofa-08/03.jpg?v=11"
        ]
      }
    ]
  }
];
